name: BPB Panel · Auto Sync & Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"   # 每天 2:30 UTC 自动执行

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch upstream BPB
        run: |
          rm -rf upstream
          git clone --depth=1 https://github.com/bia-pain-bache/BPB-Worker-Panel upstream
          (cd upstream && (git describe --tags --abbrev=0 || git rev-parse --short HEAD)) > .bpb_upstream_version

      - name: Show upstream version
        run: cat .bpb_upstream_version

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: >
            pages deploy upstream
            --project-name=${{ secrets.CF_PAGES_PROJECT_NAME }}
            --branch=production
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
